### ISSUE TITLE
Create a section in the README.md file that instructs the user how to run the project locally.

### ISSUE THREAD

**Issue by jordanhilado** [jordanhilado/Dayly#1]
Make a new section in the README.md file that tells the user step-by-step how to run the project locally on their computer.
If you want, you can make any other additional improvements to the README.md file if you feel like it.
Let me know if you have any questions, and if you would like to be assigned to this issue.

**Comment by saptarsi96** [comment]
Hi @jordanhilado, I would like to work on this.

**Comment by bhavesh-jo** [comment]
hi, @jordanhilado , can you assign it to me

**Comment by jordanhilado** [comment]
Go ahead guys! @saptarsi96 @Wittty-Panda

**Comment by saptarsi96** [comment]
Hi @jordanhilado can you please check PR #7? I think you need to merge mine changes with the one done by @Nirali0029.
